---
name: Gabriel 
surname: Rambanapasi
position: "Fixed Income Analyst"
# address: 
# pronouns: she/her
phone: +27 625 838423 
# www: gabriel.rams44@gmail.com
email: "gabriel.rams44@gmail.com"
twitter: 
github: Rambanapasi
linkedin: Gabriel Rambanapasi
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::latexcv:
    theme: classic
---

```{r setup, include=FALSE}
library(tidyverse)
library(vitae)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

```

# Work Experience

```{r}
tribble(
  ~Year, ~Type, ~Desc,
 2019, "Fixed Income Analyst ", "Contribute significanctly to the investment process by constructing investmnet stratgeies and guide portfolio construction.",
 2017 , "Fixed Income Dealer", "Mainly executed trades in line with investment strategy. Invloved relatiopship building with brokers, delaers and custodias foe best execution.", 
 2016,"Product Development Intern", "Routinely collaborated in cross departmental projects to produce products that increase stock exchange visibility and investor acitivity"
# ) %>% 
#   brief_entries(
#     glue::glue("Experience {Type}"),
#     Year, 
#     Desc
  )
```

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "CFA Level 3 Candidate", "2023", "Chartered Financial Analyst Institute", "Charlotte, United States", 
  "MSc Financial Economics", "2023", "Stellenbosch University", "Western Cape, South Africa",
  "Honours in Financial Economics", "2022", "Stellenbosch University", "Western Cape, South Africa",
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Publications

 ```{r}
# library(dplyr)
# knitr::write_bib(c("vitae", "tibble"), "packages.bib")
# 
# bibliography_entries("packages.bib") %>%
```

