---
title: "Literature review"
author: "Gabriel Rambanapasi"
date: "`r Sys.Date()`"
output: pdf_document
---

# Dividend Payment Effects On Shareholders

Dividends represent a form of capital redistribution that can either be in the form of cash or stock, which a company transfers to its shareholders. Depending on whether it is a cash or stock dividend, their impact on equity and/or cash accounts is recorded differently, thus having differing effects on stock valuation. To comprehend this, consider the fundamental law of valuation that describes equity value as a function of a company's assets and liabilities. In the case of stock dividends, a company distributes additional shares to its shareholders, usually in proportion to outstanding shares traded on the market. For example, a 5 percent stock dividend declared by a company means that an investor with 100 shares would receive additional shares. On the balance sheet, this results in a decrease in retained earnings (asset) and a simultaneous increase in shareholder equity (asset), essentially converting one form of asset into another. However, the newly issued shares dilute shareholders' ownership. On the other hand, cash dividends have a different impact, affecting both the equity and cash accounts of a company. Their declaration leads to a dividend payable (liability) on the balance sheet, a decrease in retained earnings (asset), and, once paid, a reduction in the cash balance (asset). The net effect is a reduction in the firm's value. On the ex-dividend day, theoretically, one expects the stock value of a company to decrease by a proportion equal to the declared dividends. On the part of the shareholder there should be in different on recieving a dividend as total return of holding an aseet doesnt change by the payment of dividends. As this relationship shows,  @miller  argue that a firm's value is not affected by its dividend policy, suggesting that shareholders are indifferent between dividends and capital gains. To this point, in South Africa if a company trades ex-dividend the price of the stock on aggregate drops by the amount of the dividend to be paid - implying that the one is simply swapped for the other. To show this, see Figure 1 below which shows the distribution of ex-dividend daily returns of tickers that declared final dividends since 2004.

There have been varying results emprically. Early studies by Campbell and Beranek (1955) and Durand and May (1960) have shown that stock prices consistently fall by less than the amount of the declared dividend. This is often attributed to the different tax treatment of dividends compared to capital gains. Supporting this, Elton and Gruber (1970) interpret the ex-dividend day behavior of common stock prices as evidence that differential tax rates cause investors to discount the value of taxable cash dividends relative to capital gains.More recently, Connelly (2017) conducted a study on 37 countries, concluding that price deviations are caused by frictions within markets. Similar to Elton and Gruber (1970), he stated that an ex-dividend day price drop deviates significantly from predicted values based on differential tax rates between dividends and capital gains. Moreover, through a multi-factor framework controlling for cross-country differences on ex-dividend prices, he found that stock ownership concentration, judiciary quality, and the pervasiveness of earnings management exert a significant influence on prices on ex-dividend days.In a tax-free world on dividends and capital gains, Dupuis (2019) used ex-dividend day price premiums and abnormal returns in the United Arab Emirates. The UAE market, dominated by family offices, government, and private institutions, faces adverse liquidity. By normalizing liquidity through the public free float instead of the traditional number of outstanding shares, the results showed a positive correlation to price drops. In other words, the more liquid a market, the higher the price drop on ex-dividend days. As liquid markets means more knowledge "smart"instituional investors are able to interpret information content with dividend payments.

Thus frictions suggest that there is some relelevance to dividend payments, past literature has shown some evidence of information content within the payment of dividends .@lintner1956distribution introduces the concept of smoothing dividends. This concept suggests that companies aim for stability or slight increases in dividend payments, emphasizing the importance of predictable income streams for shareholders. @gordon1959 shows taht the relationship between dividend payments and stock valuation.One could infer that dividend policies then play contribute in managing coorporate budgetting, @linter1962 extends giving a broad look into  contributes to the broader understanding of the determinants of dividend policies, exploring the intricate relationships between dividends, earnings, and financial structure. Empirical evidence thus either support opposite argument and that cannot be discounted, therefore a individual analysis is required to ascertain the context needed to explain why a comapny should have a dividend policy and its benefits to investors.

From an investment signal perspective, various studies have shown that, in fact, dividend strategies provide useful return predictive cue (c.f. Conover, Jensen, and Simpson (2016), Cornell (2012), Chen (2009) and Damodaran (2004) amongst others).






