---
title: "Literature Review"
author: "Gabriel Rambanapasi"
date: "`r Sys.Date()`"
output:
  pdf_document:
    latex_engine: pdflatex
    keep_tex: true
    template:
  html_document: default
---


# What constitutes a dividend?


Dividends are cash payouts that companies distribute to their shareholders. They can take various forms, such as cash, stock, liquidating, scrip, or property dividends. However, cash dividends are the most common type. The decision to issue dividends is typically made by the board of directors, taking into account the company's operating needs for a given financial year. When a dividend is announced, it has an impact on the financial statements of a company. It creates a liability in the form of current liabilities and decreases shareholder equity, specifically retained earnings, on the balance sheet. In other words, the company incurs an obligation to pay out the dividend, and the value of the company retained by shareholders decreases accordingly.

Cash dividends, although widely used, are not as tax-efficient as other types of dividends, such as share buybacks. Share buybacks have gained popularity in advanced economies, particularly in the United States, where they reached a high of $437 billion in 2018. Surprisingly, their adoption has been relatively slow in South Africa. According to a study by Wesson, Muller, and Ward in 2014, there were only 195 open market share repurchases announced in South Africa from 1999 to 2009. In comparison, Manconi, Peyer, and Vermaelen estimated that share repurchases constituted approximately 58% of total announcements in the United States, 15% in Canada, and 11% in Japan over the same period. This indicates a significant disparity in the adoption of share buybacks between South Africa and these other countries.  

Where else are share buybacks less popular versus dividends 
Are dividends still relevant

## Why do firms pay dividends

The issue of dividend policy and its impact on shareholder wealth has sparked debates and opposing arguments in financial literature. On one hand, the dividend puzzle suggests that dividends reduce equity value and make investors worse off. According to this view, dividends can be seen as a reward for investors who bear the risk associated with their investments. Additionally, dividends can be considered a return on investment rather than relying solely on capital gains. Various literature has emerged trying to solve the puzzel, either supporting irrelevance or relevance in dividend payments.The Modigliani-Miller (MM) theory opines that dividends are irrelevant, it argues that shareholders are indifferent to dividend payments, implying that there is no optimal dividend policy. They contend that all dividend policies are equally good and thus payments of dividends could easily be reinvested in shares and make no difference to share holder wealth. However, the MM theorem fails to consider real-world market imperfections that may give relevance to dividend payments. Global assets market face multiple constraints or imperfections namely flotation costs, transaction costs (e.g., taxes and flotation costs), information asymmetry, and principal-agent problems. 

Tax preferences play a role in the argument for dividend relevance. Different investors may be attracted to different stocks based on their tax treatments, thus investors choose stocks based on their individual investment needs. However, supporters of the MM theorem argue that changes in dividend policy should not significantly impact stock prices due to the substitution effect. According to this effect, allocation decisions of firms occur almost simultaneously, resulting in a net zero effect on prices. Flotation costs refer to the opportunity costs incurred by a firm when paying dividends. By distributing dividends, companies forego opportunities to expand their operations using retained earnings. In a world without flotation costs, as suggested by the MM theorem, management would be indifferent between issuing dividends and borrowing from the market. However, in reality, external financing comes at a higher cost, leading to trade-offs in dividend policy decisions. 

Information asymmetry between shareholders and managers is another factor that gives relevance to dividend payments. Investors rely on dividend announcements to assess a company's stock price. Dividend signaling conveys information about the company's quality. Investors compare dividend announcements to historical levels while considering company fundamentals. However, there is a risk of manipulation by management, making the dividend signal imperfect for determining share prices. Extending the argument on information asymmetry leads to the principal-agent problem, where management and shareholders may have differing goals for the use of retained earnings, leading to conflicts. The free cash flow hypothesis suggests that dividend payments force management to raise capital from external sources, which increases borrowing costs and scrutiny from capital markets. This, in turn, reduces management's ability to make sub optimal investments.
  

# When Would Dividends Matter 

Studies in dividend signalling for returns can be divided into two broad categories: academic return signalling studies or the more practitioner‐oriented long‐term return studies. For the former Fama and French (1988), found that increasing predictive power has a positive correlation to the forecast horizon, that is,  extending forecasts from months to years induced more predictive power. Subsequent studies suggest otherwise, Bekaert and Ang (2001) used dividend yield, earnings yield and short rate to predict stock return by imposing a constant risk preimuim to examine the finite sample evidence on predictability, they posit no evidence of long term predictability once finite sample influence was taken into account. Moreover, Ang and Bekaert (2006) found similar results thus suggesting that dividend yield ceases to be a good predictor of subsequent return. A possible explanation for decreasing predictive power could be the use of share buy‐backs to return capital to shareholder, as distributing capital through these methods reduces dividend yield contribution to total return  (Robertson and Wright, 2006). 

The practitioner oriented literature is investigate returns of long term strategies of systematic dividend portfolios and is more concerned with long‐term returns investment strategies. A popular strategy is the "Dogs of the Dow (DOD)". DOD is a investment strategy that involves creating a portfolio of top 10 highest paying dividend stock on the Dow Jones Industrial Index, at the start of the year (based on dividends paid in the last 12 months). The holding period is typically 12 months with the same procedure repeated the following year, therefore adjustments to portfolios will only occur once a year. There have been multiple variations of this study across different time periods and jurisdictions with significant results that the DOD or some variation of a high yield dividend strategy against the market index provides superior risk adjusted return, examples of the studies are the following (Alles and Sheng, 2008, in Australia; Visscher and Filbeck, 2003, in Canada; Kotkamp and Otte, 2001, in Germany; Wang et al., 2011, in China; Da Silva, 2001, in Latin America).




